### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by marijang** [happyDemon/UsrLastly#1]
In your middleware

if($user=  app('UsrLastlyUser')->getUser() != false)

$user value is "true" so when you call app('UsrLastlyRepository')->store($user, $request);
he dosent know $user->getKey()

i set in middleware

$user = app('UsrLastlyUser')->getUser()
if($user != false)

and then works

Thanks

**Comment by happyDemon** [comment]
thanks for this, I've incorporated it into the repo ^^
